{
  am_pm_abbreviated => [
    "BN",
    "PN",
  ],
  available_formats => {
    Bh => "h B",
    Bhm => "h:mm B",
    Bhms => "h:mm:ss B",
    E => "ccc",
    EBh => "E h B",
    EBhm => "E h:mm B",
    EBhms => "E h:mm:ss B",
    EHm => "E HH:mm",
    EHms => "E HH:mm:ss",
    Ed => "d, E",
    Eh => "E h\N{U+202f}a",
    Ehm => "E h:mm\N{U+202f}a",
    Ehms => "E h:mm:ss\N{U+202f}a",
    Gy => "G y",
    GyM => "G M/y",
    GyMEd => "G d/M/y, E",
    GyMMM => "G MMM y",
    GyMMMEd => "G d MMM y, E",
    GyMMMd => "G d MMM, y",
    GyMd => "G d/M/y",
    H => "HH",
    Hm => "HH:mm",
    Hms => "HH:mm:ss",
    Hmsv => "HH:mm:ss v",
    Hmv => "HH:mm v",
    Hv => "HH'h' v",
    M => "L",
    MEd => "d/M, E",
    MMM => "LLL",
    MMMEd => "d MMM, E",
    "MMMMW-count-one" => "'hefteya' W'an' 'ya' MMMM'\N{U+00ea}'",
    "MMMMW-count-other" => "'hefteya' W'an' 'ya' MMMM'\N{U+00ea}'",
    MMMMd => "d'\N{U+00ea}' MMMM'\N{U+00ea}'",
    MMMd => "d MMM",
    Md => "dd.MM",
    d => "d",
    h => "h\N{U+202f}a",
    hm => "h:mm\N{U+202f}a",
    hms => "h:mm:ss\N{U+202f}a",
    hmsv => "h:mm:ss\N{U+202f}a v",
    hmv => "h:mm\N{U+202f}a v",
    hv => "h\N{U+202f}a v",
    ms => "mm:ss",
    y => "y",
    yM => "MM.y",
    yMEd => "dd.MM.y, E",
    yMMM => "MMM, y",
    yMMMEd => "d MMM y, E",
    yMMMM => "MMMM'a' y'an'",
    yMMMd => "d MMM, y",
    yMd => "dd.MM.y",
    yQQQ => "QQQ, y",
    yQQQQ => "QQQQ 'ya' y'an'",
    "yw-count-one" => "'hefteya' w'an' 'ya' Y'an'",
    "yw-count-other" => "'hefteya' w'an' 'ya' Y'an'",
  },
  code => "ku-Latn-IQ",
  date_format_full => "EEEE, d'\N{U+00ea}' MMMM'a' y'an'",
  date_format_long => "d'\N{U+00ea}' MMMM'a' y'an'",
  date_format_medium => "d MMM, y",
  date_format_short => "dd.MM.y",
  datetime_format_full => "{1} {0}",
  datetime_format_long => "{1} {0}",
  datetime_format_medium => "{1} {0}",
  datetime_format_short => "{1} {0}",
  day_format_abbreviated => [
    "d\N{U+015f}m",
    "s\N{U+015f}m",
    "\N{U+00e7}\N{U+015f}m",
    "p\N{U+015f}m",
    "\N{U+00ee}n\N{U+00ee}",
    "\N{U+015f}em",
    "y\N{U+015f}m",
  ],
  day_format_narrow => [
    "D",
    "S",
    "\N{U+00c7}",
    "P",
    "\N{U+00ce}",
    "\N{U+015e}",
    "Y",
  ],
  day_format_wide => [
    "du\N{U+015f}em",
    "s\N{U+00ea}\N{U+015f}em",
    "\N{U+00e7}ar\N{U+015f}em",
    "p\N{U+00ea}nc\N{U+015f}em",
    "\N{U+00ee}n\N{U+00ee}",
    "\N{U+015f}em\N{U+00ee}",
    "yek\N{U+015f}em",
  ],
  day_stand_alone_abbreviated => [
    "d\N{U+015f}m",
    "s\N{U+015f}m",
    "\N{U+00e7}\N{U+015f}m",
    "p\N{U+015f}m",
    "\N{U+00ee}n\N{U+00ee}",
    "\N{U+015f}em",
    "y\N{U+015f}m",
  ],
  day_stand_alone_narrow => [
    "D",
    "S",
    "\N{U+00c7}",
    "P",
    "\N{U+00ce}",
    "\N{U+015e}",
    "Y",
  ],
  day_stand_alone_wide => [
    "du\N{U+015f}em",
    "s\N{U+00ea}\N{U+015f}em",
    "\N{U+00e7}ar\N{U+015f}em",
    "p\N{U+00ea}nc\N{U+015f}em",
    "\N{U+00ee}n\N{U+00ee}",
    "\N{U+015f}em\N{U+00ee}",
    "yek\N{U+015f}em",
  ],
  era_abbreviated => [
    "BM",
    "PM",
  ],
  era_narrow => [
    "BM",
    "PM",
  ],
  era_wide => [
    "Ber\N{U+00ee} M\N{U+00ee}lad\N{U+00ea}",
    "Pi\N{U+015f}t\N{U+00ee} M\N{U+00ee}lad\N{U+00ea}",
  ],
  first_day_of_week => 6,
  glibc_date_1_format => "%a %b %e %H:%M:%S %Z %Y",
  glibc_date_format => "%m/%d/%y",
  glibc_datetime_format => "%a %b %e %H:%M:%S %Y",
  glibc_time_12_format => "%I:%M:%S %p",
  glibc_time_format => "%H:%M:%S",
  language => "Kurdish",
  month_format_abbreviated => [
    "rbn",
    "sbt",
    "adr",
    "nsn",
    "gln",
    "hzr",
    "trm",
    "tbx",
    "\N{U+00ee}ln",
    "cot",
    "mjd",
    "brf",
  ],
  month_format_narrow => [
    "R",
    "S",
    "A",
    "N",
    "G",
    "H",
    "T",
    "T",
    "\N{U+00ce}",
    "C",
    "M",
    "B",
  ],
  month_format_wide => [
    "r\N{U+00ea}bendan",
    "sibat",
    "adar",
    "n\N{U+00ee}san",
    "gulan",
    "hez\N{U+00ee}ran",
    "t\N{U+00ee}rmeh",
    "tebax",
    "\N{U+00ee}lon",
    "cotmeh",
    "mijdar",
    "berfanbar",
  ],
  month_stand_alone_abbreviated => [
    "rbn",
    "sbt",
    "adr",
    "nsn",
    "gln",
    "hzr",
    "trm",
    "tbx",
    "\N{U+00ee}ln",
    "cot",
    "mjd",
    "brf",
  ],
  month_stand_alone_narrow => [
    "R",
    "S",
    "A",
    "N",
    "G",
    "H",
    "T",
    "T",
    "\N{U+00ce}",
    "C",
    "M",
    "B",
  ],
  month_stand_alone_wide => [
    "r\N{U+00ea}bendan",
    "sibat",
    "adar",
    "n\N{U+00ee}san",
    "gulan",
    "hez\N{U+00ee}ran",
    "t\N{U+00ee}rmeh",
    "tebax",
    "\N{U+00ee}lon",
    "cotmeh",
    "mijdar",
    "berfanbar",
  ],
  name => "Kurdish Iraq Latin",
  native_language => "kurd\N{U+00ee} (kurmanc\N{U+00ee})",
  native_name => "kurd\N{U+00ee} (kurmanc\N{U+00ee}) \N{U+00ce}raq lat\N{U+00ee}n\N{U+00ee}",
  native_script => "lat\N{U+00ee}n\N{U+00ee}",
  native_territory => "\N{U+00ce}raq",
  native_variant => undef,
  quarter_format_abbreviated => [
    "\N{U+00c7}1",
    "\N{U+00c7}2",
    "\N{U+00c7}3",
    "\N{U+00c7}4",
  ],
  quarter_format_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_format_wide => [
    "\N{U+00e7}aryeka 1\N{U+00ea}",
    "\N{U+00e7}aryeka 2an",
    "\N{U+00e7}aryeka 3an",
    "\N{U+00e7}aryeka 4an",
  ],
  quarter_stand_alone_abbreviated => [
    "\N{U+00c7}1",
    "\N{U+00c7}2",
    "\N{U+00c7}3",
    "\N{U+00c7}4",
  ],
  quarter_stand_alone_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_stand_alone_wide => [
    "\N{U+00e7}aryeka 1\N{U+00ea}",
    "\N{U+00e7}aryeka 2an",
    "\N{U+00e7}aryeka 3an",
    "\N{U+00e7}aryeka 4an",
  ],
  script => "Latin",
  territory => "Iraq",
  time_format_full => "HH:mm:ss zzzz",
  time_format_long => "HH:mm:ss z",
  time_format_medium => "HH:mm:ss",
  time_format_short => "HH:mm",
  variant => undef,
  version => 48,
}
