{
  am_pm_abbreviated => [
    "AM",
    "PM",
  ],
  available_formats => {
    Bh => "h B",
    Bhm => "h:mm B",
    Bhms => "h:mm:ss B",
    E => "ccc",
    EBh => "E h B",
    EBhm => "E h:mm B",
    EBhms => "E h:mm:ss B",
    EHm => "E HH:mm",
    EHms => "E HH:mm:ss",
    Ed => "d, E",
    Eh => "E h\N{U+202f}a",
    Ehm => "E h:mm a",
    Ehms => "E h:mm:ss a",
    Gy => "G y",
    GyM => "G y-MM",
    GyMEd => "G y-MM-dd, E",
    GyMMM => "G y MMM",
    GyMMMEd => "G y MMM d, E",
    GyMMMd => "G y MMM d",
    GyMd => "G y-MM-dd",
    H => "HH",
    Hm => "HH:mm",
    Hms => "HH:mm:ss",
    Hmsv => "HH:mm:ss v",
    Hmv => "HH:mm v",
    Hv => "HH'h' v",
    M => "L",
    MEd => "MM-dd, E",
    MMM => "LLL",
    MMMEd => "MMM d, E",
    "MMMMW-count-other" => "'week' W 'of' MMMM",
    MMMMd => "MMMM d",
    MMMd => "MMM d",
    Md => "MM-dd",
    d => "d",
    h => "h\N{U+202f}a",
    hm => "h:mm\N{U+202f}a",
    hms => "h:mm:ss\N{U+202f}a",
    hmsv => "h:mm:ss\N{U+202f}a v",
    hmv => "h:mm a v",
    hv => "h\N{U+202f}a v",
    ms => "mm:ss",
    y => "y",
    yM => "y-MM",
    yMEd => "y-MM-dd, E",
    yMMM => "y MMM",
    yMMMEd => "y MMM d, E",
    yMMMM => "y MMMM",
    yMMMd => "d MMM y",
    yMd => "dd/MM/y",
    yQQQ => "y QQQ",
    yQQQQ => "y QQQQ",
    "yw-count-other" => "'week' w 'of' Y",
  },
  code => "pms-IT",
  date_format_full => "y MMMM d, EEEE",
  date_format_long => "y MMMM d",
  date_format_medium => "y MMM d",
  date_format_short => "y-MM-dd",
  datetime_format_full => "{1} {0}",
  datetime_format_long => "{1} {0}",
  datetime_format_medium => "{1} {0}",
  datetime_format_short => "{1} {0}",
  day_format_abbreviated => [
    "lun-es",
    "m\N{U+00e0}rtes",
    "merco",
    "gi\N{U+00f2}bia",
    "v\N{U+00eb}nner",
    "saba",
    "dum\N{U+00ec}nica",
  ],
  day_format_narrow => [
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
    "S",
  ],
  day_format_wide => [
    "lun-es",
    "m\N{U+00e0}rtes",
    "merco",
    "gi\N{U+00f2}bia",
    "v\N{U+00eb}nner",
    "saba",
    "dum\N{U+00ec}nica",
  ],
  day_stand_alone_abbreviated => [
    "lun-es",
    "m\N{U+00e0}rtes",
    "merco",
    "gi\N{U+00f2}bia",
    "v\N{U+00eb}nner",
    "saba",
    "dum\N{U+00ec}nica",
  ],
  day_stand_alone_narrow => [
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
    "S",
  ],
  day_stand_alone_wide => [
    "lun-es",
    "m\N{U+00e0}rtes",
    "merco",
    "gi\N{U+00f2}bia",
    "v\N{U+00eb}nner",
    "saba",
    "dum\N{U+00ec}nica",
  ],
  era_abbreviated => [
    "BCE",
    "CE",
  ],
  era_narrow => [
    "BCE",
    "CE",
  ],
  era_wide => [
    "BCE",
    "CE",
  ],
  first_day_of_week => 1,
  glibc_date_1_format => "%a %b %e %H:%M:%S %Z %Y",
  glibc_date_format => "%m/%d/%y",
  glibc_datetime_format => "%a %b %e %H:%M:%S %Y",
  glibc_time_12_format => "%I:%M:%S %p",
  glibc_time_format => "%H:%M:%S",
  language => "Piedmontese",
  month_format_abbreviated => [
    "gen\N{U+00e9}",
    "f\N{U+00eb}rv\N{U+00e9}",
    "mars",
    "avril",
    "magg",
    "giugn",
    "lugn",
    "agost",
    "st\N{U+00e8}mber",
    "utuber",
    "nov\N{U+00e8}mber",
    "dz\N{U+00e8}mber",
  ],
  month_format_narrow => [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
  ],
  month_format_wide => [
    "gen\N{U+00e9}",
    "f\N{U+00eb}rv\N{U+00e9}",
    "mars",
    "avril",
    "magg",
    "giugn",
    "lugn",
    "agost",
    "st\N{U+00e8}mber",
    "utuber",
    "nov\N{U+00e8}mber",
    "dz\N{U+00e8}mber",
  ],
  month_stand_alone_abbreviated => [
    "gen\N{U+00e9}",
    "f\N{U+00eb}rv\N{U+00e9}",
    "mars",
    "avril",
    "magg",
    "giugn",
    "lugn",
    "agost",
    "st\N{U+00e8}mber",
    "utuber",
    "nov\N{U+00e8}mber",
    "dz\N{U+00e8}mber",
  ],
  month_stand_alone_narrow => [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
  ],
  month_stand_alone_wide => [
    "gen\N{U+00e9}",
    "f\N{U+00eb}rv\N{U+00e9}",
    "mars",
    "avril",
    "magg",
    "giugn",
    "lugn",
    "agost",
    "st\N{U+00e8}mber",
    "utuber",
    "nov\N{U+00e8}mber",
    "dz\N{U+00e8}mber",
  ],
  name => "Piedmontese Italy",
  native_language => "piemont\N{U+00e8}is",
  native_name => "piemont\N{U+00e8}is Italia",
  native_script => undef,
  native_territory => "Italia",
  native_variant => undef,
  quarter_format_abbreviated => [
    "Q1",
    "Q2",
    "Q3",
    "Q4",
  ],
  quarter_format_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_format_wide => [
    "Q1",
    "Q2",
    "Q3",
    "Q4",
  ],
  quarter_stand_alone_abbreviated => [
    "Q1",
    "Q2",
    "Q3",
    "Q4",
  ],
  quarter_stand_alone_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_stand_alone_wide => [
    "Q1",
    "Q2",
    "Q3",
    "Q4",
  ],
  script => undef,
  territory => "Italy",
  time_format_full => "HH:mm:ss zzzz",
  time_format_long => "HH:mm:ss z",
  time_format_medium => "HH:mm:ss",
  time_format_short => "HH:mm",
  variant => undef,
  version => 48,
}
