{
  am_pm_abbreviated => [
    "AM",
    "PM",
  ],
  available_formats => {
    Bh => "h B",
    Bhm => "h:mm B",
    Bhms => "h:mm:ss B",
    E => "ccc",
    EBh => "E h B",
    EBhm => "E h:mm B",
    EBhms => "E h:mm:ss B",
    EHm => "E HH:mm",
    EHms => "E HH:mm:ss",
    Ed => "E, d",
    Eh => "E h\N{U+202f}a",
    Ehm => "E h:mm\N{U+202f}a",
    Ehms => "E h:mm:ss\N{U+202f}a",
    Gy => "y G",
    GyM => "MM-y G",
    GyMEd => "E, dd-MM-y G",
    GyMMM => "MMM y G",
    GyMMMEd => "E, d MMM y G",
    GyMMMd => "d MMM y G",
    GyMd => "dd-MM-y G",
    H => "HH",
    Hm => "HH:mm",
    Hms => "HH:mm:ss",
    Hmsv => "HH:mm:ss v",
    Hmv => "HH:mm v",
    Hv => "HH'h' v",
    M => "L",
    MEd => "E, dd-MM",
    MMM => "LLL",
    MMMEd => "E, d MMM",
    "MMMMW-count-other" => "'week' W 'of' MMMM",
    MMMMd => "d MMMM",
    MMMd => "d MMM",
    Md => "dd-MM",
    d => "d",
    h => "h\N{U+202f}a",
    hm => "h:mm\N{U+202f}a",
    hms => "h:mm:ss\N{U+202f}a",
    hmsv => "h:mm:ss\N{U+202f}a v",
    hmv => "h:mm\N{U+202f}a v",
    hv => "h\N{U+202f}a v",
    ms => "mm:ss",
    y => "y",
    yM => "MM-y",
    yMEd => "E, dd-MM-y",
    yMMM => "MMM y",
    yMMMEd => "E, d MMM y",
    yMMMM => "MMMM y",
    yMMMd => "d MMMM y",
    yMd => "dd-MM-y",
    yQQQ => "QQQ y",
    yQQQQ => "QQQQ y",
    "yw-count-other" => "'week' w 'of' Y",
  },
  code => "rw",
  date_format_full => "y MMMM d, EEEE",
  date_format_long => "y MMMM d",
  date_format_medium => "y MMM d",
  date_format_short => "y-MM-dd",
  datetime_format_full => "{1} {0}",
  datetime_format_long => "{1} {0}",
  datetime_format_medium => "{1} {0}",
  datetime_format_short => "{1} {0}",
  day_format_abbreviated => [
    "Mbe.",
    "Kab.",
    "Gtu.",
    "Kan.",
    "Gnu.",
    "Gnd.",
    "Cyu.",
  ],
  day_format_narrow => [
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
    "S",
  ],
  day_format_wide => [
    "Kuwa mbere",
    "Kuwa kabiri",
    "Kuwa gatatu",
    "Kuwa kane",
    "Kuwa gatanu",
    "Kuwa gatandatu",
    "Ku cyumweru",
  ],
  day_stand_alone_abbreviated => [
    "Mbe.",
    "Kab.",
    "Gtu.",
    "Kan.",
    "Gnu.",
    "Gnd.",
    "Cyu.",
  ],
  day_stand_alone_narrow => [
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
    "S",
  ],
  day_stand_alone_wide => [
    "Kuwa mbere",
    "Kuwa kabiri",
    "Kuwa gatatu",
    "Kuwa kane",
    "Kuwa gatanu",
    "Kuwa gatandatu",
    "Ku cyumweru",
  ],
  era_abbreviated => [
    "BCE",
    "CE",
  ],
  era_narrow => [
    "BCE",
    "CE",
  ],
  era_wide => [
    "BCE",
    "CE",
  ],
  first_day_of_week => 1,
  glibc_date_1_format => "%a %b %e %H:%M:%S %Z %Y",
  glibc_date_format => "%m/%d/%y",
  glibc_datetime_format => "%a %b %e %H:%M:%S %Y",
  glibc_time_12_format => "%I:%M:%S %p",
  glibc_time_format => "%H:%M:%S",
  language => "Kinyarwanda",
  month_format_abbreviated => [
    "Mut.",
    "Gas.",
    "Wer.",
    "Mat.",
    "Gic.",
    "Kam.",
    "Nya.",
    "Kan.",
    "Nze.",
    "Ukw.",
    "Ugu.",
    "Uku.",
  ],
  month_format_narrow => [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
  ],
  month_format_wide => [
    "Mutarama",
    "Gashyantare",
    "Werurwe",
    "Mata",
    "Gicurasi",
    "Kamena",
    "Nyakanga",
    "Kanama",
    "Nzeri",
    "Ukwakira",
    "Ugushyingo",
    "Ukuboza",
  ],
  month_stand_alone_abbreviated => [
    "Mut.",
    "Gas.",
    "Wer.",
    "Mat.",
    "Gic.",
    "Kam.",
    "Nya.",
    "Kan.",
    "Nze.",
    "Ukw.",
    "Ugu.",
    "Uku.",
  ],
  month_stand_alone_narrow => [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
  ],
  month_stand_alone_wide => [
    "Mutarama",
    "Gashyantare",
    "Werurwe",
    "Mata",
    "Gicurasi",
    "Kamena",
    "Nyakanga",
    "Kanama",
    "Nzeri",
    "Ukwakira",
    "Ugushyingo",
    "Ukuboza",
  ],
  name => "Kinyarwanda",
  native_language => "Ikinyarwanda",
  native_name => "Ikinyarwanda",
  native_script => undef,
  native_territory => undef,
  native_variant => undef,
  quarter_format_abbreviated => [
    "I1",
    "I2",
    "I3",
    "I4",
  ],
  quarter_format_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_format_wide => [
    "igihembwe cya mbere",
    "igihembwe cya kabiri",
    "igihembwe cya gatatu",
    "igihembwe cya kane",
  ],
  quarter_stand_alone_abbreviated => [
    "I1",
    "I2",
    "I3",
    "I4",
  ],
  quarter_stand_alone_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_stand_alone_wide => [
    "igihembwe cya mbere",
    "igihembwe cya kabiri",
    "igihembwe cya gatatu",
    "igihembwe cya kane",
  ],
  script => undef,
  territory => undef,
  time_format_full => "HH:mm:ss zzzz",
  time_format_long => "HH:mm:ss z",
  time_format_medium => "HH:mm:ss",
  time_format_short => "HH:mm",
  variant => undef,
  version => 48,
}
