{
  am_pm_abbreviated => [
    "AM",
    "PM",
  ],
  available_formats => {
    Bh => "h B",
    Bhm => "h:mm B",
    Bhms => "h:mm:ss B",
    E => "ccc",
    EBh => "E h B",
    EBhm => "E h:mm B",
    EBhms => "E h:mm:ss B",
    EHm => "E HH:mm",
    EHms => "E HH:mm:ss",
    Ed => "E d",
    Eh => "E h\N{U+202f}a",
    Ehm => "E h:mm\N{U+202f}a",
    Ehms => "E h:mm:ss\N{U+202f}a",
    Gy => "y G",
    GyM => "MM/y G",
    GyMEd => "E dd/MM/y G",
    GyMMM => "MMM y G",
    GyMMMEd => "E d MMM y G",
    GyMMMd => "d MMM y G",
    GyMd => "d/M/y G",
    H => "HH",
    Hm => "HH:mm",
    Hms => "HH:mm:ss",
    Hmsv => "HH:mm:ss v",
    Hmv => "HH:mm v",
    Hv => "HH'h' v",
    M => "L",
    MEd => "E d/M",
    MMM => "LLL",
    MMMEd => "E d MMM",
    "MMMMW-count-one" => "'simana' W 'di' MMMM",
    "MMMMW-count-other" => "'simana' W 'di' MMMM",
    MMMMd => "d MMMM",
    MMMd => "d MMM",
    Md => "d/M",
    d => "d",
    h => "h\N{U+202f}a",
    hm => "h:mm\N{U+202f}a",
    hms => "h:mm:ss\N{U+202f}a",
    hmsv => "h:mm:ss\N{U+202f}a v",
    hmv => "h:mm\N{U+202f}a v",
    hv => "h\N{U+202f}a v",
    ms => "mm:ss",
    y => "y",
    yM => "M/y",
    yMEd => "E d/M/y",
    yMMM => "MMM y",
    yMMMEd => "E d MMM y",
    yMMMM => "MMMM y",
    yMMMd => "d MMM y",
    yMd => "d/M/y",
    yQQQ => "QQQ y",
    yQQQQ => "QQQQ 'd\N{U+00fb}' y",
    "yw-count-one" => "'simana' w 'd\N{U+00fb}' Y",
    "yw-count-other" => "'simana' w 'd\N{U+00fb}' Y",
  },
  code => "scn",
  date_format_full => "EEEE d MMMM y",
  date_format_long => "d MMMM y",
  date_format_medium => "d MMM y",
  date_format_short => "d/M/yy",
  datetime_format_full => "{1} {0}",
  datetime_format_long => "{1} {0}",
  datetime_format_medium => "{1} {0}",
  datetime_format_short => "{1} {0}",
  day_format_abbreviated => [
    "lun",
    "mar",
    "mer",
    "jov",
    "ven",
    "sab",
    "dum",
  ],
  day_format_narrow => [
    "l",
    "m",
    "m",
    "j",
    "v",
    "s",
    "d",
  ],
  day_format_wide => [
    "lunnid\N{U+00ec}a",
    "martid\N{U+00ec}a",
    "mercurid\N{U+00ec}a",
    "jovid\N{U+00ec}a",
    "vennirid\N{U+00ec}a",
    "s\N{U+00e0}bbatu",
    "dum\N{U+00ec}nica",
  ],
  day_stand_alone_abbreviated => [
    "lun",
    "mar",
    "mer",
    "jov",
    "ven",
    "sab",
    "dum",
  ],
  day_stand_alone_narrow => [
    "l",
    "m",
    "m",
    "j",
    "v",
    "s",
    "d",
  ],
  day_stand_alone_wide => [
    "lunnid\N{U+00ec}a",
    "martid\N{U+00ec}a",
    "mercurid\N{U+00ec}a",
    "jovid\N{U+00ec}a",
    "vennirid\N{U+00ec}a",
    "s\N{U+00e0}bbatu",
    "dum\N{U+00ec}nica",
  ],
  era_abbreviated => [
    "p.C.",
    "d.C.",
  ],
  era_narrow => [
    "pC",
    "dC",
  ],
  era_wide => [
    "prima di Cristu",
    "doppu di Cristu",
  ],
  first_day_of_week => 1,
  glibc_date_1_format => "%a %b %e %H:%M:%S %Z %Y",
  glibc_date_format => "%m/%d/%y",
  glibc_datetime_format => "%a %b %e %H:%M:%S %Y",
  glibc_time_12_format => "%I:%M:%S %p",
  glibc_time_format => "%H:%M:%S",
  language => "Sicilian",
  month_format_abbreviated => [
    "jin",
    "fri",
    "mar",
    "apr",
    "maj",
    "giu",
    "gnt",
    "agu",
    "sit",
    "utt",
    "nuv",
    "dic",
  ],
  month_format_narrow => [
    "J",
    "F",
    "M",
    "A",
    "M",
    "G",
    "G",
    "A",
    "S",
    "U",
    "N",
    "D",
  ],
  month_format_wide => [
    "jinnaru",
    "frivaru",
    "marzu",
    "aprili",
    "maju",
    "giugnu",
    "giugnettu",
    "agustu",
    "sitt\N{U+00e8}mmiru",
    "utt\N{U+00f9}viru",
    "nuv\N{U+00e8}mmiru",
    "dic\N{U+00e8}mmiru",
  ],
  month_stand_alone_abbreviated => [
    "jin",
    "fri",
    "mar",
    "apr",
    "maj",
    "giu",
    "gnt",
    "agu",
    "sit",
    "utt",
    "nuv",
    "dic",
  ],
  month_stand_alone_narrow => [
    "J",
    "F",
    "M",
    "A",
    "M",
    "G",
    "G",
    "A",
    "S",
    "U",
    "N",
    "D",
  ],
  month_stand_alone_wide => [
    "jinnaru",
    "frivaru",
    "marzu",
    "aprili",
    "maju",
    "giugnu",
    "giugnettu",
    "agustu",
    "sitt\N{U+00e8}mmiru",
    "utt\N{U+00f9}viru",
    "nuv\N{U+00e8}mmiru",
    "dic\N{U+00e8}mmiru",
  ],
  name => "Sicilian",
  native_language => "sicilianu",
  native_name => "sicilianu",
  native_script => undef,
  native_territory => undef,
  native_variant => undef,
  quarter_format_abbreviated => [
    "1T",
    "2T",
    "3T",
    "4T",
  ],
  quarter_format_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_format_wide => [
    "1\N{U+1d58} trimestri",
    "2\N{U+1d58} trimestri",
    "3\N{U+1d58} trimestri",
    "4\N{U+1d58} trimestri",
  ],
  quarter_stand_alone_abbreviated => [
    "1T",
    "2T",
    "3T",
    "4T",
  ],
  quarter_stand_alone_narrow => [
    1,
    2,
    3,
    4,
  ],
  quarter_stand_alone_wide => [
    "1\N{U+1d58} trimestri",
    "2\N{U+1d58} trimestri",
    "3\N{U+1d58} trimestri",
    "4\N{U+1d58} trimestri",
  ],
  script => undef,
  territory => undef,
  time_format_full => "HH:mm:ss zzzz",
  time_format_long => "HH:mm:ss z",
  time_format_medium => "HH:mm:ss",
  time_format_short => "HH:mm",
  variant => undef,
  version => 48,
}
